/**
 * This file is generated by the Angular 2 template compiler.
 * Do not edit.
 */
 /* tslint:disable */

import * as import0 from '@angular/core/src/render/api';
import * as import1 from '@angular/core/src/linker/view';
import * as import2 from '@angular/core/src/linker/element';
import * as import3 from './cpus.component';
import * as import4 from '@angular/core/src/linker/view_utils';
import * as import5 from '@angular/core/src/di/injector';
import * as import6 from '@angular/core/src/linker/view_type';
import * as import7 from '@angular/core/src/change_detection/change_detection';
import * as import8 from './cpu.service';
import * as import9 from '@angular/core/src/metadata/view';
import * as import10 from '@angular/core/src/linker/component_factory';
var renderType_CpusComponent_Host:import0.RenderComponentType = (null as any);
class _View_CpusComponent_Host0 extends import1.AppView<any> {
  _el_0:any;
  /*private*/ _appEl_0:import2.AppElement;
  _CpusComponent_0_4:import3.CpusComponent;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_CpusComponent_Host0,renderType_CpusComponent_Host,import6.ViewType.HOST,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    this._el_0 = this.selectOrCreateHostElement('app-cpu',rootSelector,(null as any));
    this._appEl_0 = new import2.AppElement(0,(null as any),this,this._el_0);
    var compView_0:any = viewFactory_CpusComponent0(this.viewUtils,this.injector(0),this._appEl_0);
    this._CpusComponent_0_4 = new import3.CpusComponent(this.parentInjector.get(import8.CpuService));
    this._appEl_0.initComponent(this._CpusComponent_0_4,[],compView_0);
    compView_0.create(this._CpusComponent_0_4,this.projectableNodes,(null as any));
    this.init([].concat([this._el_0]),[this._el_0],[],[]);
    return this._appEl_0;
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import3.CpusComponent) && (0 === requestNodeIndex))) { return this._CpusComponent_0_4; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    if (((this.numberOfChecks === 0) && !throwOnChange)) { this._CpusComponent_0_4.ngOnInit(); }
    this.detectContentChildrenChanges(throwOnChange);
    this.detectViewChildrenChanges(throwOnChange);
  }
}
function viewFactory_CpusComponent_Host0(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<any> {
  if ((renderType_CpusComponent_Host === (null as any))) { (renderType_CpusComponent_Host = viewUtils.createRenderComponentType('',0,import9.ViewEncapsulation.None,[],{})); }
  return new _View_CpusComponent_Host0(viewUtils,parentInjector,declarationEl);
}
export const CpusComponentNgFactory:import10.ComponentFactory<import3.CpusComponent> = new import10.ComponentFactory<import3.CpusComponent>('app-cpu',viewFactory_CpusComponent_Host0,import3.CpusComponent);
const styles_CpusComponent:any[] = ['./cpus.scss'];
var renderType_CpusComponent:import0.RenderComponentType = (null as any);
class _View_CpusComponent0 extends import1.AppView<import3.CpusComponent> {
  _el_0:any;
  _text_1:any;
  _el_2:any;
  _text_3:any;
  _el_4:any;
  _text_5:any;
  _el_6:any;
  _text_7:any;
  _el_8:any;
  _text_9:any;
  _text_10:any;
  _el_11:any;
  _text_12:any;
  _el_13:any;
  _text_14:any;
  _text_15:any;
  _el_16:any;
  _text_17:any;
  _text_18:any;
  _el_19:any;
  _text_20:any;
  _text_21:any;
  _el_22:any;
  _text_23:any;
  _text_24:any;
  _el_25:any;
  _text_26:any;
  _text_27:any;
  _el_28:any;
  _text_29:any;
  _text_30:any;
  _el_31:any;
  _text_32:any;
  _text_33:any;
  _el_34:any;
  _text_35:any;
  _text_36:any;
  _el_37:any;
  _text_38:any;
  _text_39:any;
  _el_40:any;
  _text_41:any;
  _text_42:any;
  _el_43:any;
  _text_44:any;
  _text_45:any;
  _text_46:any;
  _text_47:any;
  _el_48:any;
  _text_49:any;
  _el_50:any;
  _text_51:any;
  _text_52:any;
  _el_53:any;
  _text_54:any;
  _el_55:any;
  _text_56:any;
  _text_57:any;
  _el_58:any;
  _text_59:any;
  _text_60:any;
  _el_61:any;
  _text_62:any;
  _text_63:any;
  _el_64:any;
  _text_65:any;
  _text_66:any;
  _el_67:any;
  _text_68:any;
  _text_69:any;
  _el_70:any;
  _text_71:any;
  _text_72:any;
  _el_73:any;
  _text_74:any;
  _text_75:any;
  _el_76:any;
  _text_77:any;
  _text_78:any;
  _el_79:any;
  _text_80:any;
  _text_81:any;
  _el_82:any;
  _text_83:any;
  _text_84:any;
  _el_85:any;
  _text_86:any;
  _text_87:any;
  _text_88:any;
  _text_89:any;
  _el_90:any;
  _text_91:any;
  _el_92:any;
  _text_93:any;
  _text_94:any;
  _el_95:any;
  _text_96:any;
  _el_97:any;
  _text_98:any;
  _text_99:any;
  _el_100:any;
  _text_101:any;
  _text_102:any;
  _el_103:any;
  _text_104:any;
  _text_105:any;
  _el_106:any;
  _text_107:any;
  _text_108:any;
  _el_109:any;
  _text_110:any;
  _text_111:any;
  _el_112:any;
  _text_113:any;
  _text_114:any;
  _el_115:any;
  _text_116:any;
  _text_117:any;
  _el_118:any;
  _text_119:any;
  _text_120:any;
  _el_121:any;
  _text_122:any;
  _text_123:any;
  _el_124:any;
  _text_125:any;
  _text_126:any;
  _el_127:any;
  _text_128:any;
  _text_129:any;
  _el_130:any;
  _text_131:any;
  _text_132:any;
  _el_133:any;
  _text_134:any;
  _text_135:any;
  _el_136:any;
  _text_137:any;
  _text_138:any;
  _el_139:any;
  _text_140:any;
  _text_141:any;
  _el_142:any;
  _text_143:any;
  _text_144:any;
  _el_145:any;
  _text_146:any;
  _text_147:any;
  _el_148:any;
  _text_149:any;
  _text_150:any;
  _el_151:any;
  _text_152:any;
  _text_153:any;
  _text_154:any;
  _text_155:any;
  _el_156:any;
  _text_157:any;
  _el_158:any;
  _text_159:any;
  _text_160:any;
  _el_161:any;
  _text_162:any;
  _el_163:any;
  _text_164:any;
  _text_165:any;
  _el_166:any;
  _text_167:any;
  _text_168:any;
  _el_169:any;
  _text_170:any;
  _text_171:any;
  _el_172:any;
  _text_173:any;
  _text_174:any;
  _el_175:any;
  _text_176:any;
  _text_177:any;
  _el_178:any;
  _text_179:any;
  _text_180:any;
  _el_181:any;
  _text_182:any;
  _text_183:any;
  _el_184:any;
  _text_185:any;
  _text_186:any;
  _el_187:any;
  _text_188:any;
  _text_189:any;
  _el_190:any;
  _text_191:any;
  _text_192:any;
  _el_193:any;
  _text_194:any;
  _text_195:any;
  _el_196:any;
  _text_197:any;
  _text_198:any;
  _el_199:any;
  _text_200:any;
  _text_201:any;
  _el_202:any;
  _text_203:any;
  _text_204:any;
  _el_205:any;
  _text_206:any;
  _text_207:any;
  _text_208:any;
  _text_209:any;
  _text_210:any;
  _el_211:any;
  _text_212:any;
  _el_213:any;
  _text_214:any;
  _el_215:any;
  _text_216:any;
  _el_217:any;
  _text_218:any;
  _text_219:any;
  _el_220:any;
  _text_221:any;
  _el_222:any;
  _text_223:any;
  _text_224:any;
  _text_225:any;
  _text_226:any;
  _el_227:any;
  _text_228:any;
  _el_229:any;
  _text_230:any;
  _el_231:any;
  _text_232:any;
  _text_233:any;
  _text_234:any;
  _el_235:any;
  _text_236:any;
  _el_237:any;
  _text_238:any;
  _el_239:any;
  _text_240:any;
  _text_241:any;
  _el_242:any;
  _text_243:any;
  _el_244:any;
  _text_245:any;
  _text_246:any;
  _text_247:any;
  _text_248:any;
  _text_249:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_CpusComponent0,renderType_CpusComponent,import6.ViewType.COMPONENT,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    const parentRenderNode:any = this.renderer.createViewRoot(this.declarationAppElement.nativeElement);
    this._el_0 = this.renderer.createElement(parentRenderNode,'div',(null as any));
    this.renderer.setElementAttribute(this._el_0,'class','container-fluid');
    this._text_1 = this.renderer.createText(this._el_0,'\n    ',(null as any));
    this._el_2 = this.renderer.createElement(this._el_0,'div',(null as any));
    this.renderer.setElementAttribute(this._el_2,'class','row header');
    this._text_3 = this.renderer.createText(this._el_2,'\n      ',(null as any));
    this._el_4 = this.renderer.createElement(this._el_2,'div',(null as any));
    this.renderer.setElementAttribute(this._el_4,'class','col-md-6');
    this._text_5 = this.renderer.createText(this._el_4,'\n        \n        ',(null as any));
    this._el_6 = this.renderer.createElement(this._el_4,'div',(null as any));
    this.renderer.setElementAttribute(this._el_6,'class','row');
    this._text_7 = this.renderer.createText(this._el_6,'\n          ',(null as any));
    this._el_8 = this.renderer.createElement(this._el_6,'div',(null as any));
    this.renderer.setElementAttribute(this._el_8,'class','col-md-2');
    this._text_9 = this.renderer.createText(this._el_8,'1',(null as any));
    this._text_10 = this.renderer.createText(this._el_6,'\n          ',(null as any));
    this._el_11 = this.renderer.createElement(this._el_6,'div',(null as any));
    this.renderer.setElementAttribute(this._el_11,'class','col-md-10');
    this._text_12 = this.renderer.createText(this._el_11,'\n            ',(null as any));
    this._el_13 = this.renderer.createElement(this._el_11,'span',(null as any));
    this.renderer.setElementAttribute(this._el_13,'class','white');
    this._text_14 = this.renderer.createText(this._el_13,'[',(null as any));
    this._text_15 = this.renderer.createText(this._el_11,'\n            ',(null as any));
    this._el_16 = this.renderer.createElement(this._el_11,'span',(null as any));
    this.renderer.setElementAttribute(this._el_16,'class','green');
    this._text_17 = this.renderer.createText(this._el_16,'|',(null as any));
    this._text_18 = this.renderer.createText(this._el_11,'\n            ',(null as any));
    this._el_19 = this.renderer.createElement(this._el_11,'span',(null as any));
    this.renderer.setElementAttribute(this._el_19,'class','green');
    this._text_20 = this.renderer.createText(this._el_19,'|',(null as any));
    this._text_21 = this.renderer.createText(this._el_11,'\n            ',(null as any));
    this._el_22 = this.renderer.createElement(this._el_11,'span',(null as any));
    this.renderer.setElementAttribute(this._el_22,'class','green');
    this._text_23 = this.renderer.createText(this._el_22,'|',(null as any));
    this._text_24 = this.renderer.createText(this._el_11,'\n            ',(null as any));
    this._el_25 = this.renderer.createElement(this._el_11,'span',(null as any));
    this.renderer.setElementAttribute(this._el_25,'class','green');
    this._text_26 = this.renderer.createText(this._el_25,'|',(null as any));
    this._text_27 = this.renderer.createText(this._el_11,'\n            ',(null as any));
    this._el_28 = this.renderer.createElement(this._el_11,'span',(null as any));
    this.renderer.setElementAttribute(this._el_28,'class','green');
    this._text_29 = this.renderer.createText(this._el_28,'|',(null as any));
    this._text_30 = this.renderer.createText(this._el_11,'\n            ',(null as any));
    this._el_31 = this.renderer.createElement(this._el_11,'span',(null as any));
    this.renderer.setElementAttribute(this._el_31,'class','red');
    this._text_32 = this.renderer.createText(this._el_31,'|',(null as any));
    this._text_33 = this.renderer.createText(this._el_11,'\n            ',(null as any));
    this._el_34 = this.renderer.createElement(this._el_11,'span',(null as any));
    this.renderer.setElementAttribute(this._el_34,'class','red');
    this._text_35 = this.renderer.createText(this._el_34,'|',(null as any));
    this._text_36 = this.renderer.createText(this._el_11,'\n            ',(null as any));
    this._el_37 = this.renderer.createElement(this._el_11,'span',(null as any));
    this.renderer.setElementAttribute(this._el_37,'class','green');
    this._text_38 = this.renderer.createText(this._el_37,'|',(null as any));
    this._text_39 = this.renderer.createText(this._el_11,'\n            ',(null as any));
    this._el_40 = this.renderer.createElement(this._el_11,'span',(null as any));
    this.renderer.setElementAttribute(this._el_40,'class','white');
    this._text_41 = this.renderer.createText(this._el_40,'34%',(null as any));
    this._text_42 = this.renderer.createText(this._el_11,'\n            ',(null as any));
    this._el_43 = this.renderer.createElement(this._el_11,'span',(null as any));
    this.renderer.setElementAttribute(this._el_43,'class','white');
    this._text_44 = this.renderer.createText(this._el_43,']',(null as any));
    this._text_45 = this.renderer.createText(this._el_11,'\n          ',(null as any));
    this._text_46 = this.renderer.createText(this._el_6,'\n        ',(null as any));
    this._text_47 = this.renderer.createText(this._el_4,'\n\n\n        ',(null as any));
    this._el_48 = this.renderer.createElement(this._el_4,'div',(null as any));
    this.renderer.setElementAttribute(this._el_48,'class','row');
    this._text_49 = this.renderer.createText(this._el_48,'\n          ',(null as any));
    this._el_50 = this.renderer.createElement(this._el_48,'div',(null as any));
    this.renderer.setElementAttribute(this._el_50,'class','col-md-2');
    this._text_51 = this.renderer.createText(this._el_50,'2',(null as any));
    this._text_52 = this.renderer.createText(this._el_48,'\n          ',(null as any));
    this._el_53 = this.renderer.createElement(this._el_48,'div',(null as any));
    this.renderer.setElementAttribute(this._el_53,'class','col-md-10');
    this._text_54 = this.renderer.createText(this._el_53,'\n            ',(null as any));
    this._el_55 = this.renderer.createElement(this._el_53,'span',(null as any));
    this.renderer.setElementAttribute(this._el_55,'class','white');
    this._text_56 = this.renderer.createText(this._el_55,'[',(null as any));
    this._text_57 = this.renderer.createText(this._el_53,'\n            ',(null as any));
    this._el_58 = this.renderer.createElement(this._el_53,'span',(null as any));
    this.renderer.setElementAttribute(this._el_58,'class','green');
    this._text_59 = this.renderer.createText(this._el_58,'|',(null as any));
    this._text_60 = this.renderer.createText(this._el_53,'\n            ',(null as any));
    this._el_61 = this.renderer.createElement(this._el_53,'span',(null as any));
    this.renderer.setElementAttribute(this._el_61,'class','green');
    this._text_62 = this.renderer.createText(this._el_61,'|',(null as any));
    this._text_63 = this.renderer.createText(this._el_53,'\n            ',(null as any));
    this._el_64 = this.renderer.createElement(this._el_53,'span',(null as any));
    this.renderer.setElementAttribute(this._el_64,'class','green');
    this._text_65 = this.renderer.createText(this._el_64,'|',(null as any));
    this._text_66 = this.renderer.createText(this._el_53,'\n            ',(null as any));
    this._el_67 = this.renderer.createElement(this._el_53,'span',(null as any));
    this.renderer.setElementAttribute(this._el_67,'class','green');
    this._text_68 = this.renderer.createText(this._el_67,'|',(null as any));
    this._text_69 = this.renderer.createText(this._el_53,'\n            ',(null as any));
    this._el_70 = this.renderer.createElement(this._el_53,'span',(null as any));
    this.renderer.setElementAttribute(this._el_70,'class','green');
    this._text_71 = this.renderer.createText(this._el_70,'|',(null as any));
    this._text_72 = this.renderer.createText(this._el_53,'\n            ',(null as any));
    this._el_73 = this.renderer.createElement(this._el_53,'span',(null as any));
    this.renderer.setElementAttribute(this._el_73,'class','red');
    this._text_74 = this.renderer.createText(this._el_73,'|',(null as any));
    this._text_75 = this.renderer.createText(this._el_53,'\n            ',(null as any));
    this._el_76 = this.renderer.createElement(this._el_53,'span',(null as any));
    this.renderer.setElementAttribute(this._el_76,'class','red');
    this._text_77 = this.renderer.createText(this._el_76,'|',(null as any));
    this._text_78 = this.renderer.createText(this._el_53,'\n            ',(null as any));
    this._el_79 = this.renderer.createElement(this._el_53,'span',(null as any));
    this.renderer.setElementAttribute(this._el_79,'class','green');
    this._text_80 = this.renderer.createText(this._el_79,'|',(null as any));
    this._text_81 = this.renderer.createText(this._el_53,'\n            ',(null as any));
    this._el_82 = this.renderer.createElement(this._el_53,'span',(null as any));
    this.renderer.setElementAttribute(this._el_82,'class','white');
    this._text_83 = this.renderer.createText(this._el_82,'30%',(null as any));
    this._text_84 = this.renderer.createText(this._el_53,'\n            ',(null as any));
    this._el_85 = this.renderer.createElement(this._el_53,'span',(null as any));
    this.renderer.setElementAttribute(this._el_85,'class','white');
    this._text_86 = this.renderer.createText(this._el_85,']',(null as any));
    this._text_87 = this.renderer.createText(this._el_53,'\n          ',(null as any));
    this._text_88 = this.renderer.createText(this._el_48,'\n        ',(null as any));
    this._text_89 = this.renderer.createText(this._el_4,'\n\n        ',(null as any));
    this._el_90 = this.renderer.createElement(this._el_4,'div',(null as any));
    this.renderer.setElementAttribute(this._el_90,'class','row');
    this._text_91 = this.renderer.createText(this._el_90,'\n          ',(null as any));
    this._el_92 = this.renderer.createElement(this._el_90,'div',(null as any));
    this.renderer.setElementAttribute(this._el_92,'class','col-md-2');
    this._text_93 = this.renderer.createText(this._el_92,'Mem',(null as any));
    this._text_94 = this.renderer.createText(this._el_90,'\n          ',(null as any));
    this._el_95 = this.renderer.createElement(this._el_90,'div',(null as any));
    this.renderer.setElementAttribute(this._el_95,'class','col-md-10');
    this._text_96 = this.renderer.createText(this._el_95,'\n            ',(null as any));
    this._el_97 = this.renderer.createElement(this._el_95,'span',(null as any));
    this.renderer.setElementAttribute(this._el_97,'class','white');
    this._text_98 = this.renderer.createText(this._el_97,'[',(null as any));
    this._text_99 = this.renderer.createText(this._el_95,'\n            ',(null as any));
    this._el_100 = this.renderer.createElement(this._el_95,'span',(null as any));
    this.renderer.setElementAttribute(this._el_100,'class','green');
    this._text_101 = this.renderer.createText(this._el_100,'|',(null as any));
    this._text_102 = this.renderer.createText(this._el_95,'\n            ',(null as any));
    this._el_103 = this.renderer.createElement(this._el_95,'span',(null as any));
    this.renderer.setElementAttribute(this._el_103,'class','green');
    this._text_104 = this.renderer.createText(this._el_103,'|',(null as any));
    this._text_105 = this.renderer.createText(this._el_95,'\n            ',(null as any));
    this._el_106 = this.renderer.createElement(this._el_95,'span',(null as any));
    this.renderer.setElementAttribute(this._el_106,'class','green');
    this._text_107 = this.renderer.createText(this._el_106,'|',(null as any));
    this._text_108 = this.renderer.createText(this._el_95,'\n            ',(null as any));
    this._el_109 = this.renderer.createElement(this._el_95,'span',(null as any));
    this.renderer.setElementAttribute(this._el_109,'class','green');
    this._text_110 = this.renderer.createText(this._el_109,'|',(null as any));
    this._text_111 = this.renderer.createText(this._el_95,'\n            ',(null as any));
    this._el_112 = this.renderer.createElement(this._el_95,'span',(null as any));
    this.renderer.setElementAttribute(this._el_112,'class','green');
    this._text_113 = this.renderer.createText(this._el_112,'|',(null as any));
    this._text_114 = this.renderer.createText(this._el_95,'\n            ',(null as any));
    this._el_115 = this.renderer.createElement(this._el_95,'span',(null as any));
    this.renderer.setElementAttribute(this._el_115,'class','red');
    this._text_116 = this.renderer.createText(this._el_115,'|',(null as any));
    this._text_117 = this.renderer.createText(this._el_95,'\n            ',(null as any));
    this._el_118 = this.renderer.createElement(this._el_95,'span',(null as any));
    this.renderer.setElementAttribute(this._el_118,'class','red');
    this._text_119 = this.renderer.createText(this._el_118,'|',(null as any));
    this._text_120 = this.renderer.createText(this._el_95,'\n            ',(null as any));
    this._el_121 = this.renderer.createElement(this._el_95,'span',(null as any));
    this.renderer.setElementAttribute(this._el_121,'class','green');
    this._text_122 = this.renderer.createText(this._el_121,'|',(null as any));
    this._text_123 = this.renderer.createText(this._el_95,'\n            ',(null as any));
    this._el_124 = this.renderer.createElement(this._el_95,'span',(null as any));
    this.renderer.setElementAttribute(this._el_124,'class','green');
    this._text_125 = this.renderer.createText(this._el_124,'|',(null as any));
    this._text_126 = this.renderer.createText(this._el_95,'\n            ',(null as any));
    this._el_127 = this.renderer.createElement(this._el_95,'span',(null as any));
    this.renderer.setElementAttribute(this._el_127,'class','green');
    this._text_128 = this.renderer.createText(this._el_127,'|',(null as any));
    this._text_129 = this.renderer.createText(this._el_95,'\n            ',(null as any));
    this._el_130 = this.renderer.createElement(this._el_95,'span',(null as any));
    this.renderer.setElementAttribute(this._el_130,'class','green');
    this._text_131 = this.renderer.createText(this._el_130,'|',(null as any));
    this._text_132 = this.renderer.createText(this._el_95,'\n            ',(null as any));
    this._el_133 = this.renderer.createElement(this._el_95,'span',(null as any));
    this.renderer.setElementAttribute(this._el_133,'class','green');
    this._text_134 = this.renderer.createText(this._el_133,'|',(null as any));
    this._text_135 = this.renderer.createText(this._el_95,'\n            ',(null as any));
    this._el_136 = this.renderer.createElement(this._el_95,'span',(null as any));
    this.renderer.setElementAttribute(this._el_136,'class','green');
    this._text_137 = this.renderer.createText(this._el_136,'|',(null as any));
    this._text_138 = this.renderer.createText(this._el_95,'\n            ',(null as any));
    this._el_139 = this.renderer.createElement(this._el_95,'span',(null as any));
    this.renderer.setElementAttribute(this._el_139,'class','green');
    this._text_140 = this.renderer.createText(this._el_139,'|',(null as any));
    this._text_141 = this.renderer.createText(this._el_95,'\n            ',(null as any));
    this._el_142 = this.renderer.createElement(this._el_95,'span',(null as any));
    this.renderer.setElementAttribute(this._el_142,'class','green');
    this._text_143 = this.renderer.createText(this._el_142,'|',(null as any));
    this._text_144 = this.renderer.createText(this._el_95,'\n            ',(null as any));
    this._el_145 = this.renderer.createElement(this._el_95,'span',(null as any));
    this.renderer.setElementAttribute(this._el_145,'class','green');
    this._text_146 = this.renderer.createText(this._el_145,'|',(null as any));
    this._text_147 = this.renderer.createText(this._el_95,'\n            ',(null as any));
    this._el_148 = this.renderer.createElement(this._el_95,'span',(null as any));
    this.renderer.setElementAttribute(this._el_148,'class','gray');
    this._text_149 = this.renderer.createText(this._el_148,'993MB',(null as any));
    this._text_150 = this.renderer.createText(this._el_95,'\n            ',(null as any));
    this._el_151 = this.renderer.createElement(this._el_95,'span',(null as any));
    this.renderer.setElementAttribute(this._el_151,'class','white');
    this._text_152 = this.renderer.createText(this._el_151,']',(null as any));
    this._text_153 = this.renderer.createText(this._el_95,'\n          ',(null as any));
    this._text_154 = this.renderer.createText(this._el_90,'\n        ',(null as any));
    this._text_155 = this.renderer.createText(this._el_4,'\n\n        ',(null as any));
    this._el_156 = this.renderer.createElement(this._el_4,'div',(null as any));
    this.renderer.setElementAttribute(this._el_156,'class','row');
    this._text_157 = this.renderer.createText(this._el_156,'\n          ',(null as any));
    this._el_158 = this.renderer.createElement(this._el_156,'div',(null as any));
    this.renderer.setElementAttribute(this._el_158,'class','col-md-2');
    this._text_159 = this.renderer.createText(this._el_158,'Swp',(null as any));
    this._text_160 = this.renderer.createText(this._el_156,'\n          ',(null as any));
    this._el_161 = this.renderer.createElement(this._el_156,'div',(null as any));
    this.renderer.setElementAttribute(this._el_161,'class','col-md-10');
    this._text_162 = this.renderer.createText(this._el_161,'\n            ',(null as any));
    this._el_163 = this.renderer.createElement(this._el_161,'span',(null as any));
    this.renderer.setElementAttribute(this._el_163,'class','white');
    this._text_164 = this.renderer.createText(this._el_163,'[',(null as any));
    this._text_165 = this.renderer.createText(this._el_161,'\n            ',(null as any));
    this._el_166 = this.renderer.createElement(this._el_161,'span',(null as any));
    this.renderer.setElementAttribute(this._el_166,'class','green');
    this._text_167 = this.renderer.createText(this._el_166,'|',(null as any));
    this._text_168 = this.renderer.createText(this._el_161,'\n            ',(null as any));
    this._el_169 = this.renderer.createElement(this._el_161,'span',(null as any));
    this.renderer.setElementAttribute(this._el_169,'class','green');
    this._text_170 = this.renderer.createText(this._el_169,'|',(null as any));
    this._text_171 = this.renderer.createText(this._el_161,'\n            ',(null as any));
    this._el_172 = this.renderer.createElement(this._el_161,'span',(null as any));
    this.renderer.setElementAttribute(this._el_172,'class','green');
    this._text_173 = this.renderer.createText(this._el_172,'|',(null as any));
    this._text_174 = this.renderer.createText(this._el_161,'\n            ',(null as any));
    this._el_175 = this.renderer.createElement(this._el_161,'span',(null as any));
    this.renderer.setElementAttribute(this._el_175,'class','green');
    this._text_176 = this.renderer.createText(this._el_175,'|',(null as any));
    this._text_177 = this.renderer.createText(this._el_161,'\n            ',(null as any));
    this._el_178 = this.renderer.createElement(this._el_161,'span',(null as any));
    this.renderer.setElementAttribute(this._el_178,'class','green');
    this._text_179 = this.renderer.createText(this._el_178,'|',(null as any));
    this._text_180 = this.renderer.createText(this._el_161,'\n            ',(null as any));
    this._el_181 = this.renderer.createElement(this._el_161,'span',(null as any));
    this._text_182 = this.renderer.createText(this._el_181,' ',(null as any));
    this._text_183 = this.renderer.createText(this._el_161,'\n            ',(null as any));
    this._el_184 = this.renderer.createElement(this._el_161,'span',(null as any));
    this._text_185 = this.renderer.createText(this._el_184,' ',(null as any));
    this._text_186 = this.renderer.createText(this._el_161,'\n            ',(null as any));
    this._el_187 = this.renderer.createElement(this._el_161,'span',(null as any));
    this._text_188 = this.renderer.createText(this._el_187,' ',(null as any));
    this._text_189 = this.renderer.createText(this._el_161,'\n            ',(null as any));
    this._el_190 = this.renderer.createElement(this._el_161,'span',(null as any));
    this._text_191 = this.renderer.createText(this._el_190,' ',(null as any));
    this._text_192 = this.renderer.createText(this._el_161,'\n            ',(null as any));
    this._el_193 = this.renderer.createElement(this._el_161,'span',(null as any));
    this._text_194 = this.renderer.createText(this._el_193,' ',(null as any));
    this._text_195 = this.renderer.createText(this._el_161,'\n            ',(null as any));
    this._el_196 = this.renderer.createElement(this._el_161,'span',(null as any));
    this._text_197 = this.renderer.createText(this._el_196,' ',(null as any));
    this._text_198 = this.renderer.createText(this._el_161,'\n            ',(null as any));
    this._el_199 = this.renderer.createElement(this._el_161,'span',(null as any));
    this._text_200 = this.renderer.createText(this._el_199,' ',(null as any));
    this._text_201 = this.renderer.createText(this._el_161,'\n            ',(null as any));
    this._el_202 = this.renderer.createElement(this._el_161,'span',(null as any));
    this.renderer.setElementAttribute(this._el_202,'class','gray');
    this._text_203 = this.renderer.createText(this._el_202,'63/953MB',(null as any));
    this._text_204 = this.renderer.createText(this._el_161,'\n            ',(null as any));
    this._el_205 = this.renderer.createElement(this._el_161,'span',(null as any));
    this.renderer.setElementAttribute(this._el_205,'class','white');
    this._text_206 = this.renderer.createText(this._el_205,']',(null as any));
    this._text_207 = this.renderer.createText(this._el_161,'\n          ',(null as any));
    this._text_208 = this.renderer.createText(this._el_156,'\n        ',(null as any));
    this._text_209 = this.renderer.createText(this._el_4,'\n\n      ',(null as any));
    this._text_210 = this.renderer.createText(this._el_2,'\n      ',(null as any));
    this._el_211 = this.renderer.createElement(this._el_2,'div',(null as any));
    this.renderer.setElementAttribute(this._el_211,'class','col-md-6');
    this._text_212 = this.renderer.createText(this._el_211,'\n        \n        ',(null as any));
    this._el_213 = this.renderer.createElement(this._el_211,'div',(null as any));
    this.renderer.setElementAttribute(this._el_213,'class','row');
    this._text_214 = this.renderer.createText(this._el_213,'\n          ',(null as any));
    this._el_215 = this.renderer.createElement(this._el_213,'div',(null as any));
    this.renderer.setElementAttribute(this._el_215,'class','col-md-6');
    this._text_216 = this.renderer.createText(this._el_215,'Tasks: ',(null as any));
    this._el_217 = this.renderer.createElement(this._el_215,'span',(null as any));
    this.renderer.setElementAttribute(this._el_217,'class','white');
    this._text_218 = this.renderer.createText(this._el_217,'34 33',(null as any));
    this._text_219 = this.renderer.createText(this._el_213,'\n          ',(null as any));
    this._el_220 = this.renderer.createElement(this._el_213,'div',(null as any));
    this.renderer.setElementAttribute(this._el_220,'class','col-md-6');
    this._text_221 = this.renderer.createText(this._el_220,'thr: ',(null as any));
    this._el_222 = this.renderer.createElement(this._el_220,'span',(null as any));
    this.renderer.setElementAttribute(this._el_222,'class','white');
    this._text_223 = this.renderer.createText(this._el_222,'1',(null as any));
    this._text_224 = this.renderer.createText(this._el_220,' running',(null as any));
    this._text_225 = this.renderer.createText(this._el_213,'\n        ',(null as any));
    this._text_226 = this.renderer.createText(this._el_211,'\n\n        ',(null as any));
    this._el_227 = this.renderer.createElement(this._el_211,'div',(null as any));
    this.renderer.setElementAttribute(this._el_227,'class','row');
    this._text_228 = this.renderer.createText(this._el_227,'\n          ',(null as any));
    this._el_229 = this.renderer.createElement(this._el_227,'div',(null as any));
    this.renderer.setElementAttribute(this._el_229,'class','col-md-12');
    this._text_230 = this.renderer.createText(this._el_229,'Load average: ',(null as any));
    this._el_231 = this.renderer.createElement(this._el_229,'span',(null as any));
    this.renderer.setElementAttribute(this._el_231,'class','white');
    this._text_232 = this.renderer.createText(this._el_231,'0.05, 0.17 0.21',(null as any));
    this._text_233 = this.renderer.createText(this._el_227,'\n        ',(null as any));
    this._text_234 = this.renderer.createText(this._el_211,'\n\n        ',(null as any));
    this._el_235 = this.renderer.createElement(this._el_211,'div',(null as any));
    this.renderer.setElementAttribute(this._el_235,'class','row');
    this._text_236 = this.renderer.createText(this._el_235,'\n          ',(null as any));
    this._el_237 = this.renderer.createElement(this._el_235,'div',(null as any));
    this.renderer.setElementAttribute(this._el_237,'class','col-md-12');
    this._text_238 = this.renderer.createText(this._el_237,'Uptime: ',(null as any));
    this._el_239 = this.renderer.createElement(this._el_237,'span',(null as any));
    this.renderer.setElementAttribute(this._el_239,'class','white');
    this._text_240 = this.renderer.createText(this._el_239,'20 days, 11:57:29',(null as any));
    this._text_241 = this.renderer.createText(this._el_235,'\n          ',(null as any));
    this._el_242 = this.renderer.createElement(this._el_235,'div',(null as any));
    this.renderer.setElementAttribute(this._el_242,'class','col-md-12');
    this._text_243 = this.renderer.createText(this._el_242,'\n            ',(null as any));
    this._el_244 = this.renderer.createElement(this._el_242,':svg:svg',(null as any));
    this.renderer.setElementAttribute(this._el_244,'height','120');
    this.renderer.setElementAttribute(this._el_244,'id','visualisation');
    this.renderer.setElementAttribute(this._el_244,'width','800');
    this._text_245 = this.renderer.createText(this._el_242,'\n          ',(null as any));
    this._text_246 = this.renderer.createText(this._el_235,'\n        ',(null as any));
    this._text_247 = this.renderer.createText(this._el_211,'\n\n      ',(null as any));
    this._text_248 = this.renderer.createText(this._el_2,'\n    ',(null as any));
    this._text_249 = this.renderer.createText(this._el_0,'\n  ',(null as any));
    this.init([],[
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3,
      this._el_4,
      this._text_5,
      this._el_6,
      this._text_7,
      this._el_8,
      this._text_9,
      this._text_10,
      this._el_11,
      this._text_12,
      this._el_13,
      this._text_14,
      this._text_15,
      this._el_16,
      this._text_17,
      this._text_18,
      this._el_19,
      this._text_20,
      this._text_21,
      this._el_22,
      this._text_23,
      this._text_24,
      this._el_25,
      this._text_26,
      this._text_27,
      this._el_28,
      this._text_29,
      this._text_30,
      this._el_31,
      this._text_32,
      this._text_33,
      this._el_34,
      this._text_35,
      this._text_36,
      this._el_37,
      this._text_38,
      this._text_39,
      this._el_40,
      this._text_41,
      this._text_42,
      this._el_43,
      this._text_44,
      this._text_45,
      this._text_46,
      this._text_47,
      this._el_48,
      this._text_49,
      this._el_50,
      this._text_51,
      this._text_52,
      this._el_53,
      this._text_54,
      this._el_55,
      this._text_56,
      this._text_57,
      this._el_58,
      this._text_59,
      this._text_60,
      this._el_61,
      this._text_62,
      this._text_63,
      this._el_64,
      this._text_65,
      this._text_66,
      this._el_67,
      this._text_68,
      this._text_69,
      this._el_70,
      this._text_71,
      this._text_72,
      this._el_73,
      this._text_74,
      this._text_75,
      this._el_76,
      this._text_77,
      this._text_78,
      this._el_79,
      this._text_80,
      this._text_81,
      this._el_82,
      this._text_83,
      this._text_84,
      this._el_85,
      this._text_86,
      this._text_87,
      this._text_88,
      this._text_89,
      this._el_90,
      this._text_91,
      this._el_92,
      this._text_93,
      this._text_94,
      this._el_95,
      this._text_96,
      this._el_97,
      this._text_98,
      this._text_99,
      this._el_100,
      this._text_101,
      this._text_102,
      this._el_103,
      this._text_104,
      this._text_105,
      this._el_106,
      this._text_107,
      this._text_108,
      this._el_109,
      this._text_110,
      this._text_111,
      this._el_112,
      this._text_113,
      this._text_114,
      this._el_115,
      this._text_116,
      this._text_117,
      this._el_118,
      this._text_119,
      this._text_120,
      this._el_121,
      this._text_122,
      this._text_123,
      this._el_124,
      this._text_125,
      this._text_126,
      this._el_127,
      this._text_128,
      this._text_129,
      this._el_130,
      this._text_131,
      this._text_132,
      this._el_133,
      this._text_134,
      this._text_135,
      this._el_136,
      this._text_137,
      this._text_138,
      this._el_139,
      this._text_140,
      this._text_141,
      this._el_142,
      this._text_143,
      this._text_144,
      this._el_145,
      this._text_146,
      this._text_147,
      this._el_148,
      this._text_149,
      this._text_150,
      this._el_151,
      this._text_152,
      this._text_153,
      this._text_154,
      this._text_155,
      this._el_156,
      this._text_157,
      this._el_158,
      this._text_159,
      this._text_160,
      this._el_161,
      this._text_162,
      this._el_163,
      this._text_164,
      this._text_165,
      this._el_166,
      this._text_167,
      this._text_168,
      this._el_169,
      this._text_170,
      this._text_171,
      this._el_172,
      this._text_173,
      this._text_174,
      this._el_175,
      this._text_176,
      this._text_177,
      this._el_178,
      this._text_179,
      this._text_180,
      this._el_181,
      this._text_182,
      this._text_183,
      this._el_184,
      this._text_185,
      this._text_186,
      this._el_187,
      this._text_188,
      this._text_189,
      this._el_190,
      this._text_191,
      this._text_192,
      this._el_193,
      this._text_194,
      this._text_195,
      this._el_196,
      this._text_197,
      this._text_198,
      this._el_199,
      this._text_200,
      this._text_201,
      this._el_202,
      this._text_203,
      this._text_204,
      this._el_205,
      this._text_206,
      this._text_207,
      this._text_208,
      this._text_209,
      this._text_210,
      this._el_211,
      this._text_212,
      this._el_213,
      this._text_214,
      this._el_215,
      this._text_216,
      this._el_217,
      this._text_218,
      this._text_219,
      this._el_220,
      this._text_221,
      this._el_222,
      this._text_223,
      this._text_224,
      this._text_225,
      this._text_226,
      this._el_227,
      this._text_228,
      this._el_229,
      this._text_230,
      this._el_231,
      this._text_232,
      this._text_233,
      this._text_234,
      this._el_235,
      this._text_236,
      this._el_237,
      this._text_238,
      this._el_239,
      this._text_240,
      this._text_241,
      this._el_242,
      this._text_243,
      this._el_244,
      this._text_245,
      this._text_246,
      this._text_247,
      this._text_248,
      this._text_249
    ]
    ,[],[]);
    return (null as any);
  }
}
export function viewFactory_CpusComponent0(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<import3.CpusComponent> {
  if ((renderType_CpusComponent === (null as any))) { (renderType_CpusComponent = viewUtils.createRenderComponentType('C:/github/modata/assets/app/cpus/cpus.component.html',0,import9.ViewEncapsulation.Emulated,styles_CpusComponent,{})); }
  return new _View_CpusComponent0(viewUtils,parentInjector,declarationEl);
}